spring:
  application:
    name: sl


  datasource:
    url: jdbc:h2:mem:shortlinks-db;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080
  servlet:
    context-path: /sl

url:
  domain: "http://short.ly/"
  code-length: 6

security:
  secret: "secret_key_which_should_be_long_and_secure"

#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE